# Generated by Django 3.1 on 2020-08-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_column='admin_name', max_length=128, null=True)),
                ('password', models.CharField(db_column='admin_password', max_length=128, null=True)),
            ],
            options={
                'verbose_name': '管理员账号',
                'verbose_name_plural': '管理员账号',
                'db_table': 'adminer',
            },
        ),
    ]
