# Generated by Django 3.1 on 2020-08-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stuinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuid', models.IntegerField(db_column='学号', null=True)),
                ('stuname', models.CharField(db_column='姓名', max_length=128, null=True)),
                ('gender', models.CharField(db_column='性别', max_length=128, null=True)),
                ('profession', models.CharField(db_column='专业', max_length=128, null=True)),
                ('classid', models.IntegerField(db_column='班号', null=True)),
            ],
            options={
                'verbose_name': '学生信息',
                'verbose_name_plural': '学生信息',
                'db_table': 'stuinfo',
            },
        ),
        migrations.RenameField(
            model_name='adminer',
            old_name='username',
            new_name='adminame',
        ),
    ]
