# Generated by Django 3.1 on 2020-08-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo', '0002_auto_20200813_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='courseinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField(db_column='课程号', null=True)),
                ('cname', models.CharField(db_column='课程名', max_length=128, null=True)),
                ('ctime', models.IntegerField(db_column='学时', null=True)),
                ('cscore', models.IntegerField(db_column='学分', null=True)),
                ('tname', models.CharField(db_column='授课教师', max_length=128, null=True)),
            ],
            options={
                'verbose_name': '课程信息',
                'verbose_name_plural': '课程信息',
                'db_table': 'courseinfo',
            },
        ),
        migrations.CreateModel(
            name='scoreinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField(db_column='课程号', null=True)),
                ('cname', models.CharField(db_column='课程名', max_length=128, null=True)),
                ('tname', models.CharField(db_column='授课教师', max_length=128, null=True)),
                ('stuid', models.IntegerField(db_column='学生学号', null=True)),
                ('classid', models.IntegerField(db_column='学生班号', null=True)),
                ('score', models.IntegerField(db_column='学生成绩', null=True)),
            ],
            options={
                'verbose_name': '得分信息',
                'verbose_name_plural': '得分信息',
                'db_table': 'scoreinfo',
            },
        ),
        migrations.CreateModel(
            name='teacherinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.IntegerField(db_column='教工号', null=True)),
                ('tname', models.CharField(db_column='姓名', max_length=128, null=True)),
                ('gender', models.CharField(db_column='性别', max_length=128, null=True)),
                ('profession', models.CharField(db_column='专业', max_length=128, null=True)),
                ('courseid', models.IntegerField(db_column='所授课程', null=True)),
            ],
            options={
                'verbose_name': '教师信息',
                'verbose_name_plural': '教师信息',
                'db_table': 'teacherinfo',
            },
        ),
    ]
