# Generated by Django 3.1 on 2020-08-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo', '0003_courseinfo_scoreinfo_teacherinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuinfo',
            name='stuid',
            field=models.CharField(db_column='学号', max_length=128, null=True),
        ),
    ]
