# Generated by Django 3.1 on 2020-08-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo', '0004_auto_20200814_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='cid',
            field=models.CharField(db_column='课程号', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='scoreinfo',
            name='cid',
            field=models.CharField(db_column='课程号', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='scoreinfo',
            name='classid',
            field=models.CharField(db_column='学生班号', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='courseid',
            field=models.CharField(db_column='所授课程', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='tid',
            field=models.CharField(db_column='教工号', max_length=128, null=True),
        ),
    ]
