# Generated by Django 3.1 on 2020-08-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo', '0005_auto_20200814_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='cscore',
            field=models.FloatField(db_column='学分', null=True),
        ),
    ]
