# Generated by Django 3.1 on 2020-08-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo', '0006_auto_20200814_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuinfo',
            name='password',
            field=models.CharField(db_column='密码', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='password',
            field=models.CharField(db_column='密码', max_length=128, null=True),
        ),
    ]
