# Generated by Django 3.1 on 2020-08-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo', '0007_auto_20200815_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreinfo',
            name='stuid',
            field=models.CharField(db_column='学生学号', max_length=128, null=True),
        ),
    ]
